name: Tag Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  checks:
    name: Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Check user permissions
        uses: 74th/workflow-permission-action@1.0.0
        with:
          users: dedece35,glalloue,jhertout,jules-delecour-dav,olegoaer,zippy1978
  build:
    name: Build And Release
    runs-on: ubuntu-latest
    needs: checks
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout tag "${{ github.ref_name }}"
        uses: actions/checkout@v3
        with:
          ref: ${{  github.ref_name }}
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Build project
        run: mvn -e -B clean package -DskipTests
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: ${{ steps.extract-release-notes.outputs.release_notes }}

  upload:
    name: Upload iOS Plugin
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{github.workspace}}/sonar-ios-plugin/target/*.jar
          tag: ${{ github.ref_name }}
          #overwrite: true (use only if needs to publish 'replacable' snapshots
          file_glob: true